### PR TITLE
Add Continuous Integration functionality to core #84

### PR DESCRIPTION
**Pull request by bromeostasis**
Closes getlarky/nudge#84

No real testing, but 'approved' [here](https://github.com/getlarky/nudge/issues/84#issuecomment-387755129)

### CODE REVIEW

**Comment by ishotjr** [comment]
@bromeostasis can you clarify how migrations were confirmed/verified?

**Comment by bromeostasis** [comment]
> @bromeostasis can you clarify how migrations were confirmed/verified?



@ishotjr good questions and here's why! They weren't..

@McGarveyMobile do you know if the dbmigratemanager can be called within tests? Right now we just use `SQLAlchemy().create_database()` which goes off of [database.py](https://github.com/getlarky/nudge-core/blob/1ca3ca6702767dc4195d7674e273eac1382a08a5/core/database.py#L8), right?

**Comment by ishotjr** [comment]
@bromeostasis ahaha awesome - but to clarify, they at least *ran* at app startup and just aren't verified, or ?

**Comment by McGarveyMobile** [comment]
@bromeostasis looks like it could be! Right now we just go off of the `create_database()` but we could do something like this (haven't tried):
```
from flask_migrate import Migrate, migrate, upgrade

testmigrate = Migrate(app, db)
migrate(directory='migrations')
upgrade(directory='migrations')
```

**Comment by bromeostasis** [comment]
> @bromeostasis ahaha awesome - but to clarify, they at least ran at app startup and just aren't verified, or ?

@ishotjr I don't think they were run at any point on the ci because they're not run at any point in tests. Do you think they should be? If so, we should probably do something like what RM is talking about above in a separate issue/maybe getlarky/nudge#70.

**Comment by ishotjr** [comment]
~~@bromeostasis @McGarveyMobile OK I'm getting evan more confused; I guess what I'm looking for is something like this from `nudge-push`:~~

~~https://github.com/getlarky/nudge-push/blob/47-migrations/push/test/models/test_token.js#L27~~

~~and what I found was:~~

~~https://github.com/getlarky/nudge-core/blob/1ca3ca6702767dc4195d7674e273eac1382a08a5/tests/test_locations.py#L24~~

~~so I went to find that and for some reason looked here first and found:~~

~~https://github.com/getlarky/nudge-core/blob/1ca3ca6702767dc4195d7674e273eac1382a08a5/core/database.py#L53~~

~~which contains test data, but then accidentally noticed that there's also:~~

~~https://github.com/getlarky/nudge-core/blob/1ca3ca6702767dc4195d7674e273eac1382a08a5/tests/test_locations.py#L205~~

~~which is almost the same?~~

~~OMG further confusion: there's this explicit migration in the `nudge-push` CI:~~

~~https://github.com/getlarky/nudge-push/blob/47-migrations/.travis.yml#L13~~

@McGarveyMobile let's start over: can you just explain to me how the DB is created/updated/migrated/anything - I can't tell if it's just coming from the model somehow, or ... what form of alchemy is this? 😜

**Comment by ishotjr** [comment]
*update: discussed during SU and migration w/b in own issue that ~~@bromeostasis~~ (post-SU update via Slack: @McGarveyMobile will) will create and we'll ensure that migrations run at app start via CD issue TODO*

**Pull request merged**
